const API_VERSION = '/api/v1';

const ROLES = {
  USER: 'USER',
  RESCUE_TEAM: 'RESCUE_TEAM',
  ADMIN: 'ADMIN',
};

const RESCUE_TEAM_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  EN_ROUTE: 'EN_ROUTE',
  ON_SCENE: 'ON_SCENE',
  OFFLINE: 'OFFLINE',
};

const SHELTER_STATUS = {
  AVAILABLE: 'AVAILABLE',
  FULL: 'FULL',
  CLOSED: 'CLOSED',
  UNSAFE: 'UNSAFE',
};

const HELP_REQUEST_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const HELP_REQUEST_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  EN_ROUTE: 'EN_ROUTE',
  ON_SCENE: 'ON_SCENE',
  RESOLVED: 'RESOLVED',
  CANCELLED: 'CANCELLED',
};

const HELP_REQUEST_TRANSITIONS = {
  PENDING: ['ASSIGNED', 'CANCELLED'],
  ASSIGNED: ['EN_ROUTE', 'CANCELLED'],
  EN_ROUTE: ['ON_SCENE', 'CANCELLED'],
  ON_SCENE: ['RESOLVED'],
  RESOLVED: [],
  CANCELLED: [],
};

const ROAD_STATUS = {
  OPEN: 'OPEN',
  BLOCKED: 'BLOCKED',
  HIGH_RISK: 'HIGH_RISK',
  CLOSED: 'CLOSED',
};

const RISK_LEVEL = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const REPORT_TYPE = {
  ROAD_BLOCKED: 'ROAD_BLOCKED',
  FLOODING: 'FLOODING',
  WATER_LEVEL: 'WATER_LEVEL',
  SHELTER_FULL: 'SHELTER_FULL',
  OTHER: 'OTHER',
};

const REPORT_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

const MESSAGE_SENDER_ROLE = {
  CONTROL_ROOM: 'CONTROL_ROOM',
  RESCUE_TEAM: 'RESCUE_TEAM',
};

const NOTIFICATION_TYPE = {
  RESCUE_ASSIGNED: 'RESCUE_ASSIGNED',
  RESCUE_STATUS_CHANGED: 'RESCUE_STATUS_CHANGED',
  SHELTER_CHANGED: 'SHELTER_CHANGED',
  RISK_CHANGED: 'RISK_CHANGED',
  ROUTE_CHANGED: 'ROUTE_CHANGED',
  EMERGENCY_ALERT: 'EMERGENCY_ALERT',
  REPORT_STATUS_CHANGED: 'REPORT_STATUS_CHANGED',
  NEW_HELP_REQUEST: 'NEW_HELP_REQUEST',
};

const SOCKET_EVENTS = {
  RISK_UPDATED: 'riskUpdated',
  ROUTE_UPDATED: 'routeUpdated',
  SHELTER_UPDATED: 'shelterUpdated',
  RESCUE_ASSIGNED: 'rescueAssigned',
  RESCUE_STATUS_UPDATED: 'rescueStatusUpdated',
  EMERGENCY_ALERT: 'emergencyAlert',
  NEW_HELP_REQUEST: 'newHelpRequest',
  REQUEST_CANCELLED: 'requestCancelled',
  ROAD_STATUS_CHANGED: 'roadStatusChanged',
  SHELTER_STATUS_CHANGED: 'shelterStatusChanged',
  RESCUE_STATUS_CHANGED: 'rescueStatusChanged',
  RISK_CHANGED: 'riskChanged',
  NEW_TEAM_MESSAGE: 'newTeamMessage',
  TEAM_LOCATION_UPDATED: 'teamLocationUpdated',
};

module.exports = {
  API_VERSION,
  ROLES,
  RESCUE_TEAM_STATUS,
  SHELTER_STATUS,
  HELP_REQUEST_SEVERITY,
  HELP_REQUEST_STATUS,
  HELP_REQUEST_TRANSITIONS,
  ROAD_STATUS,
  RISK_LEVEL,
  REPORT_TYPE,
  REPORT_STATUS,
  MESSAGE_SENDER_ROLE,
  NOTIFICATION_TYPE,
  SOCKET_EVENTS,
};