const env = require('../config/env');

const AI_REQUEST_TIMEOUT_MS = 3000;

const isConfigured = () => Boolean(env.AI_SERVICE_URL);

const buildMockPrediction = (input) => ({
  riskScore: null,
  riskLevel: null,
  isSimulated: true,
  isAiServiceAvailable: false,
  disclaimer:
    'AI inference service is unavailable. This is not a real prediction; no risk value has been fabricated.',
  input,
});

const requestPrediction = async (input) => {
  if (!isConfigured()) {
    return buildMockPrediction(input);
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), AI_REQUEST_TIMEOUT_MS);

  try {
    const response = await fetch(`${env.AI_SERVICE_URL}/predict`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(input),
      signal: controller.signal,
    });

    if (!response.ok) {
      throw new Error(`AI service responded with status ${response.status}`);
    }

    const result = await response.json();

    return {
      riskScore: result.riskScore,
      riskLevel: result.riskLevel,
      isSimulated: false,
      isAiServiceAvailable: true,
      disclaimer: 'Prediction generated by the AI inference service.',
      input,
    };
  } catch (err) {
    return buildMockPrediction(input);
  } finally {
    clearTimeout(timeout);
  }
};

module.exports = { requestPrediction, isConfigured };
